### ISSUE TITLE
[Feature] Login Navbar 介面

### ISSUE THREAD

**Issue by wesley100002001** [watchout-tw/console#10]
要開始做 post & patch，使用者需要先登入拿到 jwt token
therefore 需要 Login 介面

**Comment by chihaoyo** [comment]
要引入 [watchout-tw/common](https://github.com/watchout-tw/common) 了嗎

**Comment by chihaoyo** [comment]
在這裡 5869c82650bb391a6bf6d1ccaa8f995093da526c 切換到common/NavigationWithIdentity了。

Todos:
- [ ] 已經login了的話介面要記得
- [ ] 已經login了的話再按右上角的笑臉，顯示個人基本資料sidebar，可以先用modal實作？

**Comment by wesley100002001** [comment]
現在介面會記得笑臉了 :))))))

**Comment by chihaoyo** [comment]
@wesley100002001++!

**Comment by chihaoyo** [comment]
第二項priority：**LOW**

**Comment by chihaoyo** [comment]
這個應該移到 park。
