### ISSUE TITLE
編輯委員：新增選任歷史，選項會出現 UNDEFINED

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#100]
編輯委員：新增選任歷史，預設選項會整條出現 UNDEFINED
![2017-09-25 11 11 20](https://user-images.githubusercontent.com/6219477/30791014-45a2b73e-a1e2-11e7-800c-829a0529ca99.png)

按了小鉛筆 屆期 跟 變更類型 還是依舊是 UNDEFINED
![2017-09-25 11 12 03](https://user-images.githubusercontent.com/6219477/30791025-612bf862-a1e2-11e7-8cfd-94ee18722d70.png)

而且設定完無法儲存成功。

**Comment by wesley100002001** [comment]
備註欄位 (note) 在 document 上是選填，但送出之後會得到
```
message: "child \"terms\" fails because [\"terms\" at position 0 fails because [child \"note\" fails because [\"note\" is not allowed to be empty]]]" 
```
看起來是不允許 note 是空的

**Comment by wesley100002001** [comment]
已在 core 上開了 issue

**Comment by wesley100002001** [comment]
問題出在 Joi allow null 但不 allow `''`，所以在原本輸入 DB 的資料要再 patch 進去的時候，被 Joi 擋下來了。不是新資料的問題，而是原本直接透過 db 介面塞的被擋了下來。
所以解法是直接對 DB 下 query，把所有 term 裡面的  note 從 `''` 改成 `NULL`

**Comment by wesley100002001** [comment]
但目前在選任歷史做刪除還是會得到 500

**Comment by wesley100002001** [comment]
@buttom 已排除，麻煩測試

**Comment by buttom** [comment]
@wesley100002001 選項會出現 UNDEFINED的部分測試過已排除。但無法新增成功。已經另外開 #118

**Comment by buttom** [comment]
11/15 測試 ok
