### ISSUE TITLE
編輯委員：無法幫委員選擇無黨團

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#101]
編輯委員：在幫reps/45 （紀國棟）新增 2015/7/15 從國民黨開除黨籍變無黨籍時，黨團沒有「無黨團」可以選擇。所以我從資料庫先硬塞。不過塞完後台的黨團資料會顯示成 1 （無黨團的id）
![2017-09-25 12 44 52](https://user-images.githubusercontent.com/6219477/30792722-5edd2ede-a1ef-11e7-8ac2-f7be57a6a7f1.png)

**Comment by wesley100002001** [comment]
@buttom 因為在 Term_caucus 的 table 裡，第八屆 & 第九屆都沒有設定 caucus_id 為 1 的資料，所以不管選第八屆或第九屆，都不會顯示無黨團。再麻煩你確認一下～

**Comment by buttom** [comment]
@wesley100002001  懂了，那等系統上線我再修正，感謝。

**Comment by buttom** [comment]
9/29確認ok
