### ISSUE TITLE
編輯委員：選任歷史新增後儲存，會顯示編輯失敗無法儲存

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#118]
新增的畫面如下（第三筆），後面格式沒有填之前是NULL現在則是UNDEFINED，接著按儲存會顯示編輯失敗無法儲存。
<img width="1120" alt="2017-11-09 1 45 03" src="https://user-images.githubusercontent.com/6219477/32590320-70b1a064-c4df-11e7-859f-7cfd3a6cbe4b.png">

**Comment by wesley100002001** [comment]
@buttom 原來是還沒 deploy 到 staging XD 下週一會把新的 code 上到 staging，再麻煩你測～

**Comment by buttom** [comment]
@wesley100002001 好。那上了stg再通知我一下，麻煩你了。

**Comment by wesley100002001** [comment]
@buttom staging 上已上新版可以測試

**Comment by buttom** [comment]
11/15測試ok
