### ISSUE TITLE
編輯委員：政黨歷史與選任歷史的日期，從UI新增時需要不鎖會期的日期。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#119]
因為立委的政黨歷史跟選任歷史的起始或結束日期，不一定會落在「會期內」。
例如選任日期一定是從選舉年的2月1日開始，但這個日期一定不在會期內（因為剛選上還沒開始）
這兩塊如果鎖住會期，那可新增的日期會跟實際日期有落差。

**Comment by wesley100002001** [comment]
@buttom 好，所以只是因為日期會有落差，在新增的時候仍然會選會期，對吧？
我的意思是，選了一個不在第八屆內的選任日期（第八屆前幾天這樣），但會期仍然會選第八屆，是嗎？

**Comment by buttom** [comment]
@wesley100002001 
應該說選日期的部分，現在整個中控室有兩種使用情境
1.需要鎖「會期」：（不是屆期喔，屆期是第八屆第九屆，會期是第八屆第一會期這種）例如「發言日期」「提案日期」，因為「會期」才會排案，這時候才會有提案發言的發生。

2.不需要所「會期」：例如政黨歷史跟選任歷史。選任歷史的部分，一定會在「會期」內，例如第九屆開始的第一天是2016/2/1，那就任日期一定是這天。但是第九屆第一會期要到2016/2/24才開始。
政黨歷史的部分，則可能會「跨越會期」。例如某人可能在第八屆中間某一天就成為國民黨立委，假設是2015/2/1，這天正好是在第八屆第六會期跟第七會期中間的間隔時間。可是他可能第九屆才代表國民黨選上立委。所以你提到的『選了一個不在第八屆內的選任日期（第八屆前幾天這樣），但會期仍然會選第八屆』，這個在「政黨歷史」會發生。但是在「選任歷史」不會發生。

**Comment by wesley100002001** [comment]
收到，已調整，麻煩一起測

**Comment by buttom** [comment]
11/23 測試ok
