### ISSUE TITLE
編輯屆期：編輯黨團、政團的關聯政黨會失敗

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#124]
因為民進黨黨團的關聯應該包含無黨籍，剛剛beta上我想加入無黨籍，但是儲存失敗。

**Comment by staristic** [comment]
我無法重現，已成功編輯關聯
有人能提供重現條件嗎？

**Comment by buttom** [comment]
stg上編輯前的畫面
![2017-11-20 3 21 46](https://user-images.githubusercontent.com/6219477/33006769-98fa48e8-ce06-11e7-8afb-8f10556b5030.png)
然後我想說先刪除「無黨團」看看，但刪除後儲存也是失敗。

**Comment by wesley100002001** [comment]
哦哦，這個問題跟前面無法新增會期是同一個問題，問題在 dev 已經解了所以 @staristic 測不到。
等上 staging 之後再麻煩 @buttom 一併測試。
現在編輯屆期的頁面，不管做什麼操作應該都是會失敗的。

**Comment by buttom** [comment]
11/23 測試ok
