### ISSUE TITLE
新增立委：輸入基本資料後，按儲存顯示「編輯失敗」，但實際看list是有新增成功

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#126]
新增立委輸入基本資料後，按儲存顯示「編輯失敗」，但實際看list是有新增成功

**Comment by wesley100002001** [comment]
@buttom 請再 production 上再測測看

**Comment by buttom** [comment]
@wesley100002001  prd我現在不方便用假資料，但我有在stg測，還是有一樣的問題喔。stg跟prd的程式碼應該要是一模一樣的，先幫我確認程式是否有更新到stg上了。

另外更細節的問題如下，都是在stg測試。
1.如果只輸入「全名」，會顯示編輯失敗，且回到list查看實際上也是儲存失敗。但是因為必填欄位其實只有「全名」，其他都是非必填欄位，理論上姓名寫了就應該可以新增。
2.如果只輸入「全名」「生日」，會顯示編輯失敗而且也儲存失敗。
3.如果只輸入「全名」「生日」「學歷」會顯示編輯失敗，但實際回list是儲存成功。

**Comment by buttom** [comment]
2017/12/18 測試ok
