### ISSUE TITLE
編輯法案比較：不管改什麼，儲存都會顯示「編輯失敗」

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#129]
編輯法案比較不管改什麼，儲存都會失敗，重整後確認修改後的資料沒有存入。

**Comment by staristic** [comment]
因為少一欄 scale_score_max
我已經把他加到editor.js，送到pull request裡了
只是 label 的部份可能需要改一下

**Comment by wesley100002001** [comment]
PR Merged. 問題已解決，再請 Joy 測試
問題來自輸入欄位少一欄「最大分數」，此欄位的名稱再麻煩 @buttom

**Comment by buttom** [comment]
@wesley100002001 欄位名稱是指我指定名稱嗎？可以直接就用 scale_score_max 嗎？

**Comment by wesley100002001** [comment]
現在在 staging 上已經更新了，Joy 可以看一下，現在先放了「最大分數」

**Comment by buttom** [comment]
看到了。用最大分數ok～
剛剛測試已經編輯成功
