### ISSUE TITLE
編輯屆期：既有黨團、政團如果要「移除」某個關聯政黨會無法儲存

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#130]
操作流程如下
1.選擇第八屆
2.移除國民黨黨團中的親民黨與時代力量
3.按儲存顯示「編輯失敗」
4.重整後查看也確認資料沒有儲存

**Comment by wesley100002001** [comment]
這應該跟 #127 是同一個問題，預計本週修復

**Comment by wesley100002001** [comment]
#127

**Comment by wesley100002001** [comment]
@buttom 屆期現在 api 正在重構中，不管做任何測試都會失敗，所以可以先不用針對屆期測試。api 修復之後我會再標上 test needed～

**Comment by buttom** [comment]
好。其實我屆期測差不多了。那就要測試再幫我標示，謝啦。

**Comment by buttom** [comment]
2017/12/28 測試 ok
