### ISSUE TITLE
圖表：圖表列表需要多顯示「小議題」跟「關聯資料集」，不然不知道這個圖表是誰的

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#143]
圖表：圖表列表需要多顯示「小議題」跟「關聯資料集」，不然不知道這個圖表是誰的

**Comment by chihaoyo** [comment]
1. @wesley100002001 Update docs
2. @charlieworld Update CORE

**Comment by chihaoyo** [comment]
連帶處理paging的問題（https://github.com/watchout-tw/console/issues/164）

**Comment by wesley100002001** [comment]
已解決，已上 staging

**Comment by buttom** [comment]
2018/1/5測試，列表上有多出欄位，但顯示都是? （如下圖）
![2018-01-05 12 59 46](https://user-images.githubusercontent.com/6219477/34596144-62334c70-f218-11e7-9385-bef5be7a7f88.png)

**Comment by wesley100002001** [comment]
已解決，staging 上已正常

**Comment by buttom** [comment]
2018/1/9 於 stg 測試ok
