### ISSUE TITLE
中控室選單順序與用詞調整

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#144]
「內容組成」「議題實驗室」兩大選單底下的功能，實際在操作上會有以下順序性，所以希望選單可以依照這個順序性來做排列。

圖表分析報告產出流程
1.新增資料集（提案資料集 / 發言資料集）
2.選資料集設定圖表
3.選資料集與圖表設定分析報告

議題頁面產出流程
1.新增大事紀事件，選擇已存在之圖表分析報告
2.新增大事紀，設定屬於哪個大事記事件
3.新增議題綜覽，設定哪個大事記事件屬於此議題綜覽

這兩大流程，其實是一條龍要完成不同內容的組版，在新增過程中只做其中一步都無法完整組出頁面，一定要把整個流程做完。且「分析報告組版」要先做完，才能去做「議題頁組版」。所以上面「內容組成」「議題實驗室」選單希望改成「分析報告組版」，跟「議題頁組版」，兩者子選單順序如下

「分析報告組版」
1.提案資料集
2.發言資料集
3.圖表
4.數據分析報告

「議題頁組版」
1.大事紀事件
2.大事紀
3.議題縱覽

**Comment by chihaoyo** [comment]
《中控室》的功能並非只服務《議題實驗室》，選單的邏輯與順序有整體系統架構的考量。

**Comment by buttom** [comment]
這部分我希望可以討論一下。因為現在的選單對編輯操作其實流程是不順的。後台是服務編輯，應該在系統架構跟編輯流程中取得平衡，我認同中控室並非只服務議題實驗室，但現在我列的這些功能目前都只有給議題實驗室使用。現在不先討論折衷找一個平衡就把這個需求close掉。我不太能接受

**Comment by buttom** [comment]
我可以接受因為架構調整，UI上與我最早提出的規劃不同。但起碼使用邏輯要讓編輯使用的時候是順暢地。而不是改了架構後反而要編輯去用不順的流程。

**Comment by chihaoyo** [comment]
上述所提功能都不是只服務《議題實驗室》的功能，《中控室》、沃草資訊系統架構由開發團隊規劃，因此也沒有更改架構的問題。介面必須反應系統整體架構，不宜以個人主觀認知的操作流程凌駕系統架構設計。

**Comment by buttom** [comment]
總之這項需求必須要被討論，而不是沒討論就以工程主觀認知凌駕使用者操作需求就直接close掉。

即使不只服務議題實驗室，折衷作法是可以另外開一個方便議題實驗室的選單也是可以的。直接關掉需求是怎樣？使用介面重點原本就在盡量的服務使用者需求。

我指的更改架構是當初我最早提的需求中，這部分我是用使用流程的方式去規劃介面，改成現在這樣拆開我當初也說ok但是希望要方便使用流程。現在只是要求選單順序可以更便利編輯使用，結果要被你說不移以個人主觀認知的操作流程凌駕系統設計。

請問後台UI主要是誰在使用？

**Comment by chihaoyo** [comment]
沃草《中控室》的介面是給所有夥伴使用的，夥伴中的編輯也不只一位。介面、流程設計本來就是使用者需求、系統架構設計、實質開發資源之間的妥協，而設計、開發團隊負責的事就是在前述的多方「角力」之中權衡、決策、執行。

**Comment by buttom** [comment]
總之明天需要討論。在討論完之前這個需求請不要任意close掉。

**Comment by chihaoyo** [comment]
> 沃草《中控室》的介面是給所有夥伴使用的，夥伴中的編輯也不只一位。

**Comment by buttom** [comment]
總之明天需要討論。在討論完之前這個需求請不要任意close掉。因為現在的選單對我來說就是會很難使用。也造成編輯確認上的困擾，這是我在實際使用上真實遇到的問題。我只要求選單順序的調整，就可以讓操作流程有所改善，你說「介面、流程設計本來就是使用者需求、系統架構設計、實質開發資源之間的妥協」，卻又把編輯使用實際遇到的問題與提出的需求視為「不宜以個人主觀認知的操作流程凌駕系統架構設計。」，我只看到設計師的架子與傲慢。

**Comment by buttom** [comment]
關於這個需求，我只有一個要求，你要堅持架構沒關係，選單順序可以照現有的狀態不用改，但請另外提出可以解決這個組版流程不順問題的其他解法，因為這才是我提出調整選單順序背後的原因。

我使用上確實不順。這件事也必須解決，因為我已經是最熟整個資料關聯性邏輯的人了，我用的不順也代表未來我假設要交接別的人做編輯，那被交接的人一定使用上會更不順。如果有別的更好的解法，我不會堅持選單順序一定要調整。

請協助想一下是否有別的解法，明天再一起討論。

**Comment by buttom** [comment]
先用文件的方式處理。
