### ISSUE TITLE
圖表：「狀態」可以拿掉。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#145]
目前「編輯圖表」中顯示的狀態有：待確認 / 全新 / 普通 / 更新 / 封存。因為這裡的這些「狀態」不是我設計的，所以需要請工程協助釐清現在設計的這些狀態是代表什麼意義？

在上稿實務上，最初的設定圖表有設計的狀態只有上架跟下架。但是當初是因為有另外設計「樣版功能」所以才會需要再圖表上另外有狀態的切換。可是後來樣板功能拿掉了，一個分析報告要放幾個圖表，現在已經改成可以直接從「編輯數據分析報告」去選擇，在這樣的設計下，圖表本身就不用有額外的狀態切換。所以以議題實驗室現在的狀況來說，「狀態」沒有特別的作用。

又因為圖表是透過資料集的設定才能跑出圖表，所以圖表本身是否更新，應該是從資料集更新直接控制。所以目前設計的狀態看起來在實務上是對應不起來的。

欄位還是可以保留不用特別刪除，也許未來在別的專案可能會有需要用到。但是在列表上可以拿掉不顯示。

**Comment by chihaoyo** [comment]
狀態有系統架構的需求。
