### ISSUE TITLE
編輯議題綜覽 / 編輯數據分析報告：「狀態」用詞修改

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#147]
實務上比較需要的狀態應該是「正式發布」「審稿中」「草稿」三種，差異如下：
1.正式發布：前台有正式網址，所有人不管是否登入都都可以看得到
2.審稿中：前台有正式網址，但只有「系統管理員在登入狀態」才看得到，未登入者或登入但非管理員者都不能看，主要是要先內部預覽用。
3.草稿：還沒有正式網址，但資料已經存在後台。

如果做成三種很複雜，那至少需要兩種
1.正式發布：前台有正式網址，所有人不管是否登入都都可以看得到
2.草稿：沒有正式網址，但資料已經存在後台

**Comment by chihaoyo** [comment]
「待確認」、「封存」這兩個狀態，會讓該份內容在列表中隱藏，其他狀態等同正式發布。建議使用staging來完成審稿、內部review等需求。

**Comment by buttom** [comment]
這個狀態我一樣希望重新討論。如果工程對狀態有想像，應該跟編輯一起討論看編輯的實際需求如何，再來做定義。現在感覺是工程部定義後要編輯這裡一定要接受，然後真的提出的需求反而被忽略。

**Comment by chihaoyo** [comment]
目前上線的設計可以cover更多use case，這個issue最多是更動狀態名稱，並沒有重新定義狀態的必要。

**Comment by buttom** [comment]
這部分我需要當面釐清工程對這些狀態的想像跟所謂 use case 是什麼，以及我實際知道需要的 use case在你們現在設計底下是否有被涵蓋跟滿足。我的重點不在於要不要重新定義，不重新定義可以。但重點是現在的設計要已經能夠涵蓋實際可以想像得到的需求。

**Comment by chihaoyo** [comment]
1. 「待確認」代表草稿（草稿的確是個不錯的用語呢）
2. 「封存」代表下架
3. 已正式對發布的內容，分為「全新」、「普通」、「更新」三個狀態

這樣的區分應該還蠻能理解的，也能滿足《議題實驗室》及其他專案的需求。

**Comment by buttom** [comment]
如果是已發布，分為「全新」、「普通」、「更新」三個狀態的意義分別是什麼？
只看字面意思，我無法理解他們三者的差異在哪。

如果封存代表下架，能否字面上直接使用下架比較直觀？

**Comment by buttom** [comment]
明天討論到這個部分時，我會請萌萌他們明天一起進來，確認其他編輯對這些狀態的理解跟需求。

**Comment by chihaoyo** [comment]
「全新」、「更新」、「普通」想要表達的是該內容是「全新的內容」、「最近更新的內容」，還是都不是。

我不喜歡上下架的譬喻，所以使用「封存」（archived）這種比較正式的用語。

**Comment by chihaoyo** [comment]
另外，提醒這裡是GitHub上的公開repo，所有討論過程都是公開的。

**Comment by buttom** [comment]
總之用詞部分我會找其他之後會使用後台的編輯一起進來討論，因為之後使用UI介面主要還是編輯。你不喜歡上下架的譬喻說真的也是你個人的主觀。

我知道討論過程都是公開的，謝謝提醒。

**Comment by buttom** [comment]
總之用詞部分我會找其他之後會使用後台的編輯一起進來討論，因為之後使用UI介面主要還是編輯。你不喜歡上下架的譬喻說真的也是你個人的主觀。當然如果大家最後覺得用封存比較好，我也不會堅持。但這部份用詞希望讓編輯一起確認。

我知道討論過程都是公開的，謝謝提醒。

**Comment by buttom** [comment]
「全新」、「更新」、「普通」想要表達的是該內容是「全新的內容」、「最近更新的內容」，還是都不是。------>這部分以發布狀態（例如已上稿 / 已發布）搭配實際發布時間是否應該會更為準確？

所謂的「全新」假設發布時間是2017/1010。到2017/11/11還顯示「全新」語意上也是很奇怪的事。

**Comment by wesley100002001** [comment]
12/19 結論：
待確認 -> 草稿
普通 -> 已發佈

是否在 api 實做封存，再討論

**Comment by buttom** [comment]
2017/12/19 stg測試ok
