### ISSUE TITLE
編輯議題綜覽：大事記應該顯示title而非id

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#148]
現在的畫面是這樣
![2017-12-06 12 29 32](https://user-images.githubusercontent.com/6219477/33644663-2708f108-da81-11e7-9b26-007c9065957c.png)

應該要改成顯示Timeline的title，不然看不懂。

**Comment by chihaoyo** [comment]
Fixed.

**Comment by buttom** [comment]
2017/12/18 測試ok
