### ISSUE TITLE
圖表：「類型」需轉換改成顯示中文

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#149]
現在的畫面
![2017-12-06 12 34 49](https://user-images.githubusercontent.com/6219477/33644781-e1b7ab16-da81-11e7-9a10-490cd92db755.png)
需要改顯示成中文

**Comment by buttom** [comment]
2017/12/19 stg測試ok，但是文字部分能否再調整一下，直接跟前台的圖表名稱一致？
例如「法案比較得分」現在前台是「提案成份比較」，「雷達」前台是「提案戰力分析」，以此類推。

**Comment by buttom** [comment]
前後台中文對應我直接整理在下面
後台的名稱 /  前台現在的圖表名稱
法案比較得分 / 提案成份比較
雷達 / 提案戰力分析
精簡列表 / 提案簡單比較
詳細列表 / 提案完整比較
政黨分組計數 / 提案與連署名單
全體委員比例 / 委員參與度甜甜圈
政黨比例 / 政黨參與度甜甜圈
最多連署 / 提案連署之最
委員網絡 / 提案連署人際網絡
政黨發言次數統計 / 發言計數器
政黨發言比例統計 / 政黨發言百分比
委員發言立場統計 / 委員立場甜甜圈
應發言而未發言的委員 / 誰沒說話

**Comment by wesley100002001** [comment]
已修正上 staging，再麻煩測試

**Comment by buttom** [comment]
2017/12/26 測試ok
