### ISSUE TITLE
編輯圖表：「類型」與「資料集」顯示文字需修正

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#150]
1.「類型」要調整顯示成中文，現在是這，現在是這樣
<img width="208" alt="2017-12-07 11 35 31" src="https://user-images.githubusercontent.com/6219477/33697613-c51493f4-db42-11e7-8b39-5b77c7f3892c.png">

2. 「資料集」要調整顯示成資料集的「名稱」+「版本號」，現在顯示的是id
<img width="318" alt="2017-12-07 11 37 24" src="https://user-images.githubusercontent.com/6219477/33697669-0540f06c-db43-11e7-8944-cf670bc8a57f.png">

**Comment by wesley100002001** [comment]
已上 staging

**Comment by buttom** [comment]
2017/12/26 測試ok
