### ISSUE TITLE
編輯圖表：新增時「資料集」因為顯示不出來所以無法選擇，以至於無法完成圖表設定 / 介面上的欄位順序需要調整

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#155]
編輯圖表操作問題
1.新增時「資料集」因為顯示不出來所以無法選擇，以至於無法完成圖表設定
2.在操作邏輯上，提案資料集會對應固定的圖表，發言資料集也會對應固定的圖表，且兩種圖表不會重複。因此順序上應該要先選「資料集型別」跟「資料集」，才能進一步去選擇圖表的「類型」。

所以欄位上，請直接把「資料集型別」跟「資料集」放在「類型」上方。不用獨立一塊大標題標示「資料集」

上述提到的資料型別與圖表對應如下，這部分屆時也要加入過濾
【提案資料集 】（名稱請改成跟前台一致，我這裡直接列前台的圖表名稱）
1.提案成份比較
2.提案戰力分析
3.提案簡單比較
4.提案完整比較
5.提案與連署名單
6.委員參與度甜甜圈
7.政黨參與度甜甜圈
8.提案連署之最
9.提案連署人際網絡

【發言資料集 】
1.提案與連署名單
2.委員參與度甜甜圈
3.政黨參與度甜甜圈
4.提案連署之最
5.提案連署人際網絡

**Comment by chihaoyo** [comment]
To fix AbstractSelect bug.

**Comment by wesley100002001** [comment]
已修正

**Comment by buttom** [comment]
@wesley100002001 資料集可以選了，但是按儲存時上方顯示「"preview" is not allowed」，所以還是無法順利新增顯示「編輯失敗」。

**Comment by wesley100002001** [comment]
已修正

**Comment by buttom** [comment]
2017/12/26 stg 測試ok
