### ISSUE TITLE
編輯提案資料集：提案評分無法編輯

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#156]
兩個狀況
1.如果是已有的資料按編輯，提案評分這塊沒有顯示任何資料與編輯界面
2.如果是新增提案資料，因為沒有編輯界面，所以也無從編輯評分

這塊資料當初是直接進DB先塞的。

**Comment by chihaoyo** [comment]
To find bug and fix.

**Comment by wesley100002001** [comment]
已修正於 staging， @buttom 測試的時候麻煩先測試能否加新資料 -> 開啟剛新加的資料能否編輯，都沒問題的話，要麻煩重新編輯之前輸入過的提案評分

**Comment by buttom** [comment]
2017/12/27 測試結果

1.新加的資料可儲存，但是新增後重整畫面。畫面上的分數會歸0
新增儲存時的畫面
![2017-12-27 1 07 56](https://user-images.githubusercontent.com/6219477/34371314-0d8c0170-eb07-11e7-8ddc-4e5a30acc1e7.png)

新增儲存後重新整理的畫面
![2017-12-27 1 08 07](https://user-images.githubusercontent.com/6219477/34371318-10dab02e-eb07-11e7-99aa-d5e081e7d438.png)

2.編輯已存在資料（之前用DB塞的）的分數，也有上述問題。就是重整後後台看分數會歸零（不過去前台看，只要我沒有再按一次儲存，他確實有按照我前面編輯的分數顯示，主要是後台沒有顯示儲存後的分數都顯示為0）

**Comment by wesley100002001** [comment]
@buttom 分數未更新已修正於 staging，再麻煩

**Comment by buttom** [comment]
2017/12/28 stg測試，分數編輯ok。
