### ISSUE TITLE
編輯發言資料集：應發言的「會期」沒有顯示出資料

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#160]
之前是直接塞DB，不過現在在編輯發言資料集內會期都是空的，沒有顯示出DB內設定的資料。即使用介面更改了按儲存也編輯成功，儲存後重整還是顯示是空的，不過進DB看是有更新，所以是介面上沒顯示但DB有寫入成功。

**Comment by chihaoyo** [comment]
To find bug in Editor and fix.

**Comment by wesley100002001** [comment]
vue 的 watcher 跟 sync 改到了資料，gonna find it n fix it

**Comment by wesley100002001** [comment]
已修正於 staging

**Comment by buttom** [comment]
2018/1/8 stg測試ok
