### ISSUE TITLE
所有必填欄位都要標示為必填

### ISSUE THREAD

**Issue by wesley100002001** [watchout-tw/console#167]

**Comment by chihaoyo** [comment]
1. docs.core.watchout.tw
2. core.watchout.tw/docs
3. CONSOLE config
以上三者必須同步。

**Comment by chihaoyo** [comment]
其他相關issue請close。

**Comment by chihaoyo** [comment]
#163 #161

**Comment by buttom** [comment]
2018/1/5 stg測試
#163 #161 #141 
測試ok


#142
短網址沒填會顯示
child "slug" fails because ["slug" must be a string]
但短網址並沒有被標示為*

**Comment by wesley100002001** [comment]
#142 也已修正於 staging

**Comment by buttom** [comment]
2018/1/9 於 stg 測試ok
