### ISSUE TITLE
編輯提案資料集：法案比較 / 提案應顯示文字，現在是顯示id

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#171]
例如 /lab_bill_data_sets/4 如下圖
![2017-12-19 10 32 08](https://user-images.githubusercontent.com/6219477/34137858-e571c7fc-e4a7-11e7-8ba4-f5f230b4d062.png)

**Comment by wesley100002001** [comment]
這跟 #156 算是同一個 bug，要麻煩 @buttom 如果遇到這種問題的資料，要把提案清掉後重新輸入，謝謝

**Comment by buttom** [comment]
2017/12/28 stg 測試ok
