### ISSUE TITLE
編輯提案：法案比較的簡短內容希望改成可以輸入多行

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#179]
編輯提案：法案比較的簡短內容希望改成可以輸入多行（像完整內容那樣），因為有滿高頻率有些簡短內容，我整理的方式是分行條列，例如
```
2本俸當基數：50%->42%
提案基數：64%->54%
```
這種

**Comment by chihaoyo** [comment]
因為這樣要改db欄位的資料型別，所以先改成`discussion`，討論並評估此項變更的成本。

**Comment by buttom** [comment]
@chihaoyo 那是否有折衷方法，例如我怎麼輸入，他實際在前台顯示可以換行就好？這欄位允許使用<br><li>這些html 嗎？

**Comment by chihaoyo** [comment]
了解。有資料的範例可以給我參考嗎？🤔

**Comment by wesley100002001** [comment]
討論過後，由於不會影響到資料庫設計 & 前端顯示，所以可以直接支援改為多行輸入。
現在已修正，並已在 staging 上。

**Comment by buttom** [comment]
2018/1/5 stg測試ok
