### ISSUE TITLE
編輯大事紀：沒有可以把「大事紀事件」放進來的操作介面

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#190]
在DB的 event_ids 這一項，在中控室沒有設定介面。所以無法針對原有的資料編輯新增修改「大事紀事件」。新增大事紀的時候，也沒有設定介面可以把「大事紀事件」放進來

**Comment by wesley100002001** [comment]
已修正於 staging

**Comment by buttom** [comment]
2018/1/8  測試ok
