### ISSUE TITLE
編輯大事紀事件：編輯舊有的大事紀事件時，當初用DB塞的數據分析報告無法在UI上顯示

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#193]
如果是全新從介面上新增的，可以顯示。但如果是舊的就會呈現空白。

**Comment by wesley100002001** [comment]
已修正於 staging，現在是舊的看得到，但新的會是空白。
如果 @buttom 看到也是這樣狀況，就代表可以了，把新的重塞即可

**Comment by buttom** [comment]
2018/1/10 stg測試ok
