### ISSUE TITLE
編輯數據分析報告：新增全新分析報告時，出現system_db_dup_entry，顯示編輯失敗，但回列表看是編輯成功。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#202]
昨天（1/16）還可以操作。今天新增時出現「system_db_dup_entry」的訊息，以及編輯失敗的訊息。
回列表看，有新的數據分析報告出現（代表其實有新增成功），點進去看「基本資料」有寫進去，但「圖表」的資料是空的。

**Comment by wesley100002001** [comment]
好像是 API 端有問題，需要再追一下

**Comment by wesley100002001** [comment]
@buttom API 端已解決，也已上 production，再麻煩測試謝謝

**Comment by buttom** [comment]
@wesley100002001  好，但最近prd要組的圖表剛好都組完了，暫時不會「新增」，這個我等有新議題分析圖表要新增的時候再來正式測。

**Comment by wesley100002001** [comment]
好，那就先把 issue 留著

**Comment by buttom** [comment]
怕拖太久會忘記，剛剛prd新增一筆測試資料，功能ok了。
