### ISSUE TITLE
編輯提案資料集：無法新增成功

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#205]
資料都填滿了，但是會顯示「An internal server error occurred」，回列表頁確認無法新增成功。

**Comment by wesley100002001** [comment]
已修正完成～麻煩測試

**Comment by buttom** [comment]
已測試，資料全部填寫（包含短網址）可以通過。

題外話，提案資料集他是一種資料集，單獨存在不會有「頁面」，也不會像圖表需要有獨立分享的需求，且這個資料集的設計當初就是為了要產出分析圖表用，算是分析圖表的前置資料設定，所以其實這個可以不用有短網址...

不過已經有了就這樣吧，只是每次操作都要多填（且必然是亂填）一個資料就是。

**Comment by buttom** [comment]
@wesley100002001 

剛繼續測試，「新增」可以過。但是「編輯」過不了，會出現「An internal server error occurred」
可以直接上prd開 /lab_bill_data_sets/16 都不改直接按儲存就不會過了。

再麻煩確認一下問題，感謝。

**Comment by wesley100002001** [comment]
已經修好了並上 Prod 了～麻煩測試

**Comment by buttom** [comment]
操作ok
