### ISSUE TITLE
提案連署列表：新增顯示編輯成功，但是回列表頁看沒有資料

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#206]
提案：新增顯示編輯成功，但是回列表頁看沒有資料。本來以為寫入失敗，但是後來直接把 /rep_speech/rs_bills/141 後面數字換掉，資料是會撈出來的

但是這個只有針對今天新增的小議題「資通安全」才有這個問題。如果選擇之前就新增的小議題例如「長期照顧」，在列表頁上就會顯示出來，但是一旦再改回資通安全，就又會從列表頁上消失。

**Comment by wesley100002001** [comment]
這個問題應該已經解了？ @buttom

**Comment by buttom** [comment]
有顯示了。
