### ISSUE TITLE
新增編輯法案：按儲存時會等很久。看沒反應點回列表頁會發現有新增成功，可是「關聯小議題」沒寫入成功

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#207]
新增編輯法案：按儲存時會等很久。看沒反應點回列表頁會發現有新增成功，可是「關聯小議題」沒寫入成功。然後重新進去編輯設定「關聯小議題」會等很久，最後會顯示「編輯失敗」

這造成的連帶問題是在「提案連署」裡面新增法案後，沒有辦法設定法案比較（因為法案跟小議題的關聯設定失敗）。

**Comment by wesley100002001** [comment]
已修復，麻煩 Joy 測試～

另外，提案、連署那邊會有資料沒有顯示（資通法的那個），原因出在這裡，只要把關連小議題設定好，那邊的資料就會正常顯示，再麻煩 Joy 一併測試～

**Comment by buttom** [comment]
@wesley100002001  已經在prd測試了，新增跟編輯都還是會按儲存時會等很久沒反應。測試結果還是跟原本回報的狀況一樣。

**Comment by buttom** [comment]
測試ok!
