### ISSUE TITLE
新增小議題：如果有選擇關聯大議題，會儲存失敗

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#208]
新增小議題，如果有選擇關聯大議題的時候，按儲存會等很久。回list看會發現小議題已經有儲存，但跟大議題的關聯沒儲存，編輯如果選擇關聯大議題，儲存會失敗。但如果沒有選只是設定修法方向則可以儲存成功。

**Comment by wesley100002001** [comment]
已上 production～再麻煩測試

**Comment by buttom** [comment]
新增編輯都測試ok
