### ISSUE TITLE
如果 vue watch 的值拿到 null，會有 warning

### ISSUE THREAD

**Issue by wesley100002001** [watchout-tw/console#21]
目前出現在大議題、小議題、法案的 Checklist，下面以法案為例解釋：
如果點開一個現存法案，但此法案沒有任何關聯的小議題，則在 editorchecklist 的 `:model.sync="model[section.id]"` 這個值會是 null，而不是空陣列。這個行為會讓 vue 跳 warning。

但其實不影響操作，所以可以之後再修，或是如果所有法案、小議題、大議題都有關聯的東西，那就 luckily 不會被 vue 抱怨 XD

**Comment by staristic** [comment]
@wesley100002001  
有沒有辦法重現？我目前沒有看到任何warning

**Comment by wesley100002001** [comment]
現在應該是這個情況吧 XD
`如果所有法案、小議題、大議題都有關聯的東西，那就 luckily 不會被 vue 抱怨 XD`
如果已經沒有任何 warning，就可以 close 了

**Comment by wesley100002001** [comment]
應該目前 config 已經夠完整，所以不會被抱怨了，close
