### ISSUE TITLE
確認core API call request及response中的boolean

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/console#29]
@charlieworld說core在碰到型態為boolean的資料時會統一用int（0或1）來處理，也希望console在送出request時也是用int，所以console必須確認、並做適當的調整。

**Comment by chihaoyo** [comment]
好像解決了？@staristic

**Comment by staristic** [comment]
editor.js中已確認有這種情況的欄位都有接上 preparers.boolean2Int，且已驗證功能正常
