### ISSUE TITLE
PATCH payload semantics

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/console#35]
- 如果payload中有key，value是空陣列，表示要把目前的資料清空。
- 如果payload中沒有key，表示這個request沒有要更新。

這樣的語意設定應該是合理？目前console的UI應該也是按照這樣的邏輯在運作，不過還是麻煩@staristic確認一下。

**Comment by chihaoyo** [comment]
與charlie溝通後，如果是null，視為空陣列。修正於 https://github.com/watchout-tw/core/pull/61

**Comment by staristic** [comment]
目前所有已接上的功能應該都已經符合這個規則了。
