### ISSUE TITLE
管理法案比較：新增一個法案比較後，列表沒有顯示出「關聯修法方向」

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#36]
後台新增一個法案比較後，在列表沒有顯示出「關聯修法方向」。進入資料庫看時，st_title 與 act_title 與act_dir_name 與st_title 與 act_title 與act_dir_name 顯示為Null 顯示為Null。理論上只有id就可帶出title。我不太確定當時設計title也帶進來的原因，可能要重新跟 peter 確認一下。

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/core/pull/50

**Comment by buttom** [comment]
9/6 測試ok
