### ISSUE TITLE
新增法案比較：依照小議題過濾法案、修法方向

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#38]
新增法案比較：目前選擇「小議題」時，「法案」、「修法方向」會列出全部而非小議題關聯修法方向，需修正成只秀小議題關聯。

**Comment by chihaoyo** [comment]
TODO: Apply cascadeUpdate.

**Comment by chihaoyo** [comment]
b4af549e6a2cf023e38e184dcddd05a002a77056

**Comment by buttom** [comment]
9/6 測試ok
