### ISSUE TITLE
登出：登出後應統一倒回後台首頁

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#39]
後台若已經在某單元（新增畫面或列表），按右上角登出後，畫面還是會停留在該單元的畫面。後台登出後請一律導回後台「Hello, stranger. Live long and prosper.」的頁面。

**Comment by chihaoyo** [comment]
f9d0d60b2df28976dad9b7f4fc4a488301334cbe

**Comment by buttom** [comment]
9/6 測試ok
