### ISSUE TITLE
Color picker 要能夠直接輸入 hex

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/console#4]
寫一個 custom component 把 el-color-picker 包起來吧！這件事也不急。

**Comment by staristic** [comment]
我大致上解完了，但是有件事要確認一下。
我看了下 Request，送出去的 Color 的字串格式長這樣 「rgba(11, 22, 33)」
我現在改成 Hex 的格式，像是「#ABC123」，後端的 API 能吃嗎？

**Comment by chihaoyo** [comment]
可以的，API ❤️ hex，請@staristic開branch發PR！

**Comment by chihaoyo** [comment]
👍
