### ISSUE TITLE
編輯器介面需要區隔必填及選填欄位

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#42]
所有單元，必填欄位的欄位名稱請後面加 * 字號

**Comment by staristic** [comment]
使用 EditorCheckList 的時候，不知道 * 要加在哪

**Comment by chihaoyo** [comment]
@staristic 你是透過在`config/editors.js`裡面手動加註必填來做到這件事嗎？我想要一個能夠自動與db schema同步的解法。@charlie有想法嗎？

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/console/issues/106
