### ISSUE TITLE
起訖時間需要檢查重疊的情形

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#45]
新增屆期：起訖時間需要過濾看有沒有跟其他屆期重疊（可以按新增以後才提示，不一定需要做到即時提示），因為這是之後過濾發言屬於哪一屆的根據，所以不同屆期的日期不能重疊。

**Comment by chihaoyo** [comment]
暫時不處理。

**Comment by chihaoyo** [comment]
重新定義問題：
* 檢查所有含有「起訖時間」的資料
* 決定哪些資料需要檢查重疊的情形
* 開出檢查重疊的API
* 設計及實作前端的handler
