### ISSUE TITLE
編輯屆期之編輯會期：日期無法編輯

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#47]
編輯屆期之編輯會期：因為起訖時間被鎖在單天（8/23），所以無法順利把會期資料建立在屆期內的時間區間。等屆期修好這部分要重測。

**Comment by chihaoyo** [comment]
已修正。

**Comment by chihaoyo** [comment]
b13e7d9595801b842759b3dc27a7ef3dc7e07365

**Comment by buttom** [comment]
9/6 測試ok
