### ISSUE TITLE
編輯委員：按「新增實體聯絡資料」「最新」開關預設是 yes 但儲存結果是 no

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#52]
編輯委員：實體聯絡資料，按「新增實體聯絡資料」時，出現的「最新」開關預設是yes，但如果沒有去動，直接儲存，再回去看儲存的資料，都是存成no。

**Comment by chihaoyo** [comment]
57b9ea102fef5988ff6c6537e8db82ddccd1f5b9

**Comment by buttom** [comment]
9/6 測試ok
