### ISSUE TITLE
編輯委員：實體聯絡資料的電話/傳真無法儲存實際輸入的數字

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#53]
編輯委員：實體聯絡資料的電話/傳真不管當初輸入什麼，最後都會存成-1111109。編輯完還是一樣，無法儲存實際輸入的數字。
圖一：第五行，電話傳真輸入是02-1111111
![image1](https://user-images.githubusercontent.com/6219477/29607662-7efb73fe-8824-11e7-9ce6-3735e976b801.png)
圖二：存完回list再進來看，變成-1111109，編輯存完回來看也是一樣。
![image2](https://user-images.githubusercontent.com/6219477/29607661-7ef4c5f4-8824-11e7-9d4f-61fd31f21e51.png)

**Comment by chihaoyo** [comment]
@charlieworld 修正中。

**Comment by buttom** [comment]
9/6 測試ok
