### ISSUE TITLE
新增提案連署新增失敗

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#62]
新增提案連署：有填寫關聯法案/日期/字號/第一提案人類別/第一提案人，對照資料庫中必填欄位應該都有填了，但新增失敗。即使最上面所有欄位（不含底下審議進度，爭點，法案比較）都填了，還是新增失敗。

**Comment by chihaoyo** [comment]
@buttom 剛剛更新，請再測試一次。

**Comment by buttom** [comment]
@chihaoyo 剛剛測試ok了，謝啦。

**Comment by chihaoyo** [comment]
e5838fa7b1d5acd0537ce14a741b0a40dd0a9811
