### ISSUE TITLE
新增發言的所屬政黨需要自動判斷

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#63]
新增發言：當時所屬政黨，理論上，要從立委的「政黨歷史」撈出來自動判斷。但是現在還沒時間塞選舉歷史資料Orz，所以現在也只能先保持現狀（輸入發言時再自選所屬政黨），這個後面可能要想一下怎麼調整，但不會是現在警急要處理的東西，先記著。

**Comment by chihaoyo** [comment]
初步構想，使用`GET /c0ngress/date_to_rep_info`搭配`cascadeUpdate`。

**Comment by chihaoyo** [comment]
合併到 https://github.com/watchout-tw/console/issues/13
