### ISSUE TITLE
編輯提案連署「是否為法律」調整成只有新增時可設定

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#65]
編輯提案連署：「是否為法律」的項目調整成只有新增時可設定。改成到編輯的時候，就直接鎖起來，僅顯示但不可修改。因為是法律還是提案一開始確定後就不該再變了。

**Comment by chihaoyo** [comment]
cf6fdfa90fdf7e8ad9d7556947fd002ba23a3101
