### ISSUE TITLE
新增立委：預設性別女但存進去會是酷兒

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#67]
新增立委：目前性別預設是「女」，但如果都沒動，按儲存以後，會存成「酷兒」。可以直接把預設就顯示成「酷兒」就好。如果預設還是保持女，那至少儲存也要存女進去。

**Comment by wesley100002001** [comment]
@buttom 解決了，麻煩 Joy 再測一下

**Comment by buttom** [comment]
@wesley100002001  我剛測試了。我新增 reps/183
新增委員預設是顯示「100% 女性」，但查詢編輯點進去，他還是顯示「酷兒」。

**Comment by buttom** [comment]
11/23 測試，輸入「基本資料」後，按儲存顯示「編輯失敗」所以無法測試此項

**Comment by buttom** [comment]
11/23 測試。新增委員會顯示「編輯失敗」但實際list有存入（已新增 #126 ），儲存結果看起來已經解決這個儲存跟預設不一致的問題。
