### ISSUE TITLE
編輯委員：新增多委員會紀錄時會出現下拉選單失效的狀況。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#68]
編輯委員：再新增委員會歷史使用下拉選單選屆期的時候，遇到不順的狀況：
如果只新增一個不會，但要同時設定第二個的時候，選了屆期後，會期下拉選單案不出來。委員會選單也按不出來。接著連帶畫面上新增委員歷史紀錄/新增選任歷史紀錄/新增政黨歷史紀錄跟畫面最上方各單元下拉選單會一起失效。

**Comment by staristic** [comment]
沒有發現下拉選單失效的情況，但是發現其它問題

@charlieworld 
無法刪除委員會歷史，api 會回傳 error 500

**Comment by buttom** [comment]
2017/12/18測試ok
