### ISSUE TITLE
編輯提案：「第一提案人」會顯示id，而非姓名

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#69]
編輯提案：「第一提案人」會顯示id，而非姓名（第一提案人類別不管是委員，黨團，政府單位，都是一樣的狀況），且按下拉想改成別的委員時會顯示「無資料」，等於無法更改第一提案人。

**Comment by chihaoyo** [comment]
d02cf7c4512a5488e594c853f7ea7a05b9cea06b + 571e095c79848e82144cee5271a4dd014213b280 已修正，請再測試一次。

**Comment by buttom** [comment]
9/7測試，姓名顯示正常了。
