### ISSUE TITLE
新增提案：底下法案比較的「小議題」應該只秀出跟該法案關聯的小議題就好。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#71]
新增提案：底下法案比較的「小議題」直接秀出所有議題，應該只秀出跟該法案關聯的小議題就好。後面新增的提案越多會越容易在這裡出錯，希望這個可以先修。

**Comment by buttom** [comment]
我搞錯了，後來小議題移到底下跟著爭點和法案比較，先關掉issue。

**Comment by chihaoyo** [comment]
@wesley100002001 @staristic 使用`cascadeUpdate`ㄅ

**Comment by staristic** [comment]
@chihaoyo @wesley100002001 
我努力了半天發現做不出來，先前的 cascade 都是在同一個 section 裡，但是這一次是不同的 section 互相影響，請問要怎麼寫比較好？

**Comment by chihaoyo** [comment]
我收回上面的發言，用目前的`cascadeUpdate`無法解決。除非想到好的修改`cascadeUpdate`機制的方法，否則暫時不處理。

**Comment by chihaoyo** [comment]
合併到 https://github.com/watchout-tw/console/issues/13
