### ISSUE TITLE
提案列表：列表上沒有顯示出關聯小議題

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#72]
提案管理：列表上沒有顯示出關聯小議題。（如果多個可以直接顯示多個ok）

**Comment by buttom** [comment]
我搞錯了，後來小議題移到底下跟著爭點和法案比較，先關掉issue。

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/core/issues/68 core更新中。

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/core/pull/73

**Comment by buttom** [comment]
9/13測試ok
