### ISSUE TITLE
編輯提案：底下的法案比較，小議題會變成「UNDEFINED」

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#73]
編輯提案：底下的法案比較，新增儲存回來看，小議題會變成「UNDEFINED」，即使重新編輯儲存後，回來看還是一樣。
![2017-09-06 4 52 38](https://user-images.githubusercontent.com/6219477/30103074-1f946406-9324-11e7-97a5-8c796f5be618.png)

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/core/issues/71 core更新中。

**Comment by charlieworld** [comment]
此問題已修正於 C0re 的  [20170910-1]  版本中

詳見release note : 
https://github.com/watchout-tw/core/pull/77

**Comment by buttom** [comment]
9/22 測試ok
