### ISSUE TITLE
新增委員：新增政黨歷史時若選了日期，政黨跟黨團下拉選單會不正常

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#75]
新增委員：新增政黨歷史的時候，如果先設定好日期，那政黨跟黨團的下拉選單會變成無法使用（不會展開），但如果日期留空先選政黨跟黨團，則下拉選單可正常展開。

**Comment by chihaoyo** [comment]
47176f1dcb21ed00e196377ac8e3757f56805140 改寫了一個地方，請再測試一次。

**Comment by buttom** [comment]
9/7測試，下拉選單已正常。
