### ISSUE TITLE
新增委員：政黨歷史的黨團下拉選單，選項異常重複。

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#76]
新增委員：政黨歷史的黨團下拉選單，目前黨團建檔的資料是正常的（見下圖），
<img width="367" alt="2017-09-07 1 30 04" src="https://user-images.githubusercontent.com/6219477/30147387-b36c2e0a-93d0-11e7-9b69-3ffc66fb3849.png">

但是在下拉顯示的黨團資料會重複好幾個（見下圖）
<img width="707" alt="2017-09-07 1 30 41" src="https://user-images.githubusercontent.com/6219477/30147408-c8d7bc5a-93d0-11e7-8e5d-e6de214c508c.png">

**Comment by wesley100002001** [comment]
測試之後實際的狀況是，/lab/term_caucus? 以及 /lab/term_parties? 兩個 api call 都回了 7、8、9 三屆的政黨、黨團及政團，所以才會有重複

**Comment by charlieworld** [comment]
@wesley100002001  不太理解
我們沒有 
/lab/term_caucus 
/lab/term_parties
這兩個API
有辦法跟我說這個下拉選是呼叫哪個 API 還有下了哪些filter 嗎？

**Comment by charlieworld** [comment]
@wesley100002001  @chihaoyo 

查了一下 是 GET /console/lab/term_caucuses 的問題

原因是因為 第八屆的國民黨團有三個政黨

<img width="400" alt="error" src="https://i.imgur.com/1b4NM4c.png">

所以這邊的party_id 是不是沒有用到阿？  (API 沒有吐party的資訊)
感覺是要先選「黨團」，之後針對黨團下Filter，下了之後 在選政黨。

跟兩位確定一下這個問題。

PS.  我們目前有這下面四隻API 的 Docs嗎 ？？  （忘了....)
GET /console/lab/term_caucuses
GET /console/lab/term_districts
GET /console/lab/term_parties
GET /console/lab/term_sessions

**Comment by buttom** [comment]
2017/12/18測試ok
