### ISSUE TITLE
編輯小議題：修法方向新增失敗

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#78]
編輯小議題：如果該議題還沒有任何修法方向，那新增修法方向會失敗。但如果該議題之前已經設定過修法方向，則再新增更多修法方向會成功。這個最近會常用到，希望先修好。

**Comment by wesley100002001** [comment]
目前檢查前端送出去的東西是正常的，再請 @charlieworld 檢查後端

**Comment by charlieworld** [comment]
此問題已更新於 C0re 的  [20170920-1]  版本中

有些許調整，詳見release note : 
https://github.com/watchout-tw/core/pull/84

**Comment by buttom** [comment]
9/22 測試已ok
