### ISSUE TITLE
編輯小議題：新增爭點失敗

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#79]
編輯小議題：如果該議題還沒有任何爭點，那新增爭點會失敗。但如果該議題之前已經設定過爭點，則再新增更多爭點會成功。

**Comment by wesley100002001** [comment]
@charlieworld 應該是同一個 Issue

**Comment by charlieworld** [comment]
此問題已更新於 C0re 的  [20170920-1]  版本中

有些許調整，詳見release note : 
https://github.com/watchout-tw/core/pull/84

**Comment by buttom** [comment]
9/22 只要爭點跟修法方向的排序都不為0 (null) 即可新增成功。之後新增失敗應出示比較清楚的系統訊息讓操作者知道要改哪裡。
