### ISSUE TITLE
學歷下拉選單需修正以符合中選會提供的資料

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#82]
中選會提供的學歷資料一共有這些項目：博士，碩士，大學，大專，專科，高中，其他

但這跟我們現在資料庫中最高學歷下拉有一點不符合。學歷下拉目前應該不是用獨立的table的控制，目前
資料庫記錄學歷是用英文，前台才轉中文。這部分下拉選單須調整成跟中選會提供的資料一致。

**Comment by chihaoyo** [comment]
faeb42a

**Comment by buttom** [comment]
剛連進去測試，學歷下拉選單的項目還是舊的（博士/碩士/學士/高中高職/中學/小學/其他）

**Comment by chihaoyo** [comment]
應該修好囉！

**Comment by buttom** [comment]
10/23 測試 ok
