### ISSUE TITLE
新增提案資料：第一提案人類別選「政府單位」時，第一提案人的下拉會顯示沒有資料

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#85]
新增提案資料：第一提案人類別選「政府單位」時，第一提案人的下拉會顯示沒有資料，以致於無法選擇行政院（但更之前是好的，因為曾經有用過，只有選「政府單位」才有問題。黨團跟委員則正常）

**Comment by wesley100002001** [comment]
Solved.  2792cbc

**Comment by buttom** [comment]
9/29測試ok
