### ISSUE TITLE
新增提案資料：有輸入日期但沒有自動撈出對應屆期會期

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#86]
新增提案資料：選擇提案（非法案），有輸入日期但沒有自動撈出對應屆期會期。且在提案資料管理列表上，屆期也顯示為0。（之前是正常的）

**Comment by wesley100002001** [comment]
目前好像是正常？@buttom  麻煩再確認一下～

**Comment by buttom** [comment]
@wesley100002001  新增的部分看起來好了，修改的，要改一下日期讓他重抓就ok，但之前輸入的，頁碼切不過去有點困難改。我直接先對id去修正好了。
