### ISSUE TITLE
提案列表：點進去實際是page 1但底下page nav會顯示最後一頁

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#88]
提案列表：點進去實際是page1的list，但底下page nav 會顯示最後一頁（例如p3），以至於要到p3必須要先點1再點3才會切過去。

**Comment by wesley100002001** [comment]
@buttom 問題似乎已經排除？

**Comment by buttom** [comment]
@wesley100002001  還沒。不過要用這樣的操作流程才會看得到
1.先隨便點p2之後的頁面，然後選一筆進去編輯。
2.然後按上一頁回列表。或是點上面選單提案連署回去list，就會看到實際list內容是p1的，但底下nav會留在剛剛的page而非p1

**Comment by wesley100002001** [comment]
這個問題，想要透過 code refactor 來解決。
想要拿掉 List.vue 不必要的 vuex 架構…（我跪

**Comment by wesley100002001** [comment]
277e40a

**Comment by wesley100002001** [comment]
@buttom 已解決，再麻煩 Joy

**Comment by buttom** [comment]
11/1 測試 ok
