### ISSUE TITLE
單一圖表組頁面例如提案比較，網址結構是否能再簡化？

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#91]
目前網址結構是 /t/2/dr/2 ，但我發現其實前面數字不改，只改後面頁面就會換掉了。這部分是否可以簡化成一層，例如 dr/2 就好？雖然dr=2資料上是隸屬於t=2沒錯，但因為網址結構本身的英文其實對內容沒有辨識性，因此多一層 /t/2/ 反而顯得累贅。

另外，像 dr ，t ，能否替換成有意義的英文單字？例如圖表用chart，議題用issue。這對seo也會有幫助。

**Comment by chihaoyo** [comment]
https://github.com/watchout-tw/lab/issues/4
