### ISSUE TITLE
單一圖表頁需要找地方放入導覽麵包屑

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#93]
返回可以保留，但還是需要加入導覽麵包屑。為了兩個目的
1.方便使用者知道自己在哪跟理解這個網站的階層關係
2.有效率的建立網站內部連結，有助於SEO。因為麵包屑等於每個階層的link都在上面，也比較可以幫助搜尋引擎了解網站的階層關係。

**Comment by chihaoyo** [comment]
這個issue應該開在LAB：https://github.com/watchout-tw/lab/issues/5
