### ISSUE TITLE
法案比較列表：目前沒有分頁 / 超過20筆看不到也搜尋不到但DB有紀錄

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#96]
法案比較列表：目前沒有分頁，需要加上分頁，因為之後會非常多。

**Comment by wesley100002001** [comment]
這個要之後配合 API 規劃

**Comment by buttom** [comment]
stg上測試：目前不只沒有分頁，且只顯示20筆。所以超過20筆的資料完全看不到。用上面選法案搜尋找也沒有顯示。但是實際連到資料庫是有該筆資料。這會造成不知道到底資料有沒有新增成功。

**Comment by buttom** [comment]
stg上測試：目前不只沒有分頁，且只顯示20筆。所以超過20筆的資料完全看不到。用上面選法案搜尋找也沒有顯示。但是實際連到資料庫是有該筆資料。這會造成不知道到底資料有沒有新增成功。

如果暫時不加分頁，至少要把全部的法案比較列表秀出來。

**Comment by buttom** [comment]
這個改high，因為我現在新增勞基法要從這裡開始設定，會頻繁需要新增跟編輯。這裡卡住會影響後面資料新增。

**Comment by wesley100002001** [comment]
已修正，已上 staging，再麻煩 @buttom

**Comment by buttom** [comment]
2017/12/25 stg 測試ok
