### ISSUE TITLE
新增法案比較：設定法案比較量尺有時會儲存失敗

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#97]
新增法案比較：設定法案比較量尺有時會儲存失敗，但目前歸納不出特定規則。有時候是一開始新增儲存時就存失敗，有時候是編輯比較量尺後儲存失敗。但再試一次通常又會儲存成功。

**Comment by staristic** [comment]
無法重現
編輯和新增我重複試了很多 case ，沒有發現問題。
如果沒有人能重現應該可以close了

**Comment by buttom** [comment]
可能是之前比較不穩定。可以先close。後面假設有遇到我再重新回報就好。
