### ISSUE TITLE
之後後台的 LAB_Bill_Data_Set 的 scores 與 act_feature_ids 應為非必填

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#98]
目前兩個提案有關的圖表頁面資料源，以實作資料重新整理後，狀況如下
a.提案評比：要挑提案，要評分，要修法方向
b.連署關聯：要挑提案，免評分，修法方方向可有可無
而實作上有可能會有這個法案我不做評比，只做連署關聯資料表。或是評比了多個修法方向，但連署關聯不管修法方向就都抓進來。（這次集遊法，國體法都會遇到）

有可能這法案我評比的修法方向只涵蓋部分提案，但連署關聯可能只是想呈現當時有多少人都有提案修過法，不一定跟修法方向有關。這種狀況就要新增兩個資料來源。

不太確定這是否有必要牽扯到資料庫結構重構，總之先記錄下來。

**Comment by chihaoyo** [comment]
@buttom 討論、筆記型的issue可以使用`discussion`這個label 😄

**Comment by buttom** [comment]
實際操作時發現可以用「修法方方向」來「群組」哪些提案要拉入資料源。所以此點不用再討論。
