### ISSUE TITLE
編輯委員：刪除選任歷史後儲存會失敗

### ISSUE THREAD

**Issue by buttom** [watchout-tw/console#99]
編輯委員：刪除選任歷史後，按儲存會出現「編輯失敗」，重整後確認沒有儲存成功。

**Comment by staristic** [comment]
@charlieworld  
patch 的 api 在刪除委員的時候會跳錯誤訊息：
error:"Internal Server Error"
message:"An internal server error occurred"
已確認傳過去的格式是對的

**Comment by wesley100002001** [comment]
@buttom 已排除，麻煩測試

**Comment by buttom** [comment]
@wesley100002001 在beta console 測試，還是失敗。

**Comment by buttom** [comment]
11/15測試ok
